### PR TITLE
Add 5th line-sensor for the line-following task

### PR DESCRIPTION
**Pull request by Krishna-13-cyber**
This PR includes the accommodation of the 5th line sensor array which has been recently introduced in the WallE bot for line following task using the tcrt sensors.

### CODE REVIEW

**Comment by Jamm02** [comment]
Please update the PR with proper commits, @Krishna-13-cyber; you should not commit modifications that you intend to revert in the next commit.

**Review by Jamm02 — CHANGES_REQUESTED** [review]
Please update the PR with proper commits, @Krishna-13-cyber; you should not commit modifications that you intend to revert in the next commit.

**Review by Jamm02 — APPROVED** [review]
PR can be merged.

**Comment by gautam-dev-maker** [comment]
Since #82 achieves the purpose of updating `pin_defs.h` for LSA, this PR can be closed.

Thank you.

**Pull request closed without merging**
