### PR TITLE
Made the readme nicer

### PR DESCRIPTION
**Pull request by SAtacker**
Readme Modified as per https://github.com/roshanlam/ReadMeTemplate

### CODE REVIEW

**Comment by VedantParanjape** [comment]
@SAtacker Placement of badges is wrong, link to documentation is wrong

**Comment by SAtacker** [comment]
Could you elaborate more about placement of badges ?
Laukik's https://github.com/laukik-hase/OTA_update_STM32_using_ESP32 seems to have similar placement i.e. at the top

**Comment by SAtacker** [comment]
Are there any more changes to be made ?

**Comment by VedantParanjape** [comment]
@SAtacker good enough

**Pull request merged**
